In [2]:
import numpy as np
import pandas as pd

In [3]:
movies=pd.read_csv('tmdb_5000_movies.csv')
crew=pd.read_csv('tmdb_5000_credits.csv')

In [4]:
crew.head()
movies.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [5]:
movies=movies.merge(crew,on='title')

In [6]:
movies.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  ... runtime  \
0  [{"name": "Ingenious Film Partners", "id": 289...  ...   162.0   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...  ...   169.0   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...  ...   148.0   
3  [{"name": "Legendary Pictures", "id": 923}, {"...  ...   165.0   
4        [{"name": "Walt Disney Pictures", "id": 2}]  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count movie_id  \
0                                    Avatar          7.2      11800    19995   
1  Pirates of the Caribbean: At World's End          6.9       4500      285   
2                                   Spectre          6.3       4466   206647   
3                     The Dark Knight Rises          7.6       9106    49026   
4                               John Carter          6.1       2124    49529   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...

In [7]:
movies=movies[['id','title','crew','overview','cast','genres','keywords']]

movies.head()

In [8]:
movies.head()

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                                crew  \
0  [{"credit_id": "52fe48009251416c750aca23", "de...   
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...   
2  [{"credit_id": "54805967c3a36829b5002c41", "de...   
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...   
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  
0  [{"id": 1463, "name": "culture clash"}, {"id":...  
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...  
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...  
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...  
4  [{"id": 818, "name": "based on novel"}, {"id":...

In [9]:
movies.dropna()

id                                     title  \
0      19995                                    Avatar   
1        285  Pirates of the Caribbean: At World's End   
2     206647                                   Spectre   
3      49026                     The Dark Knight Rises   
4      49529                               John Carter   
...      ...                                       ...   
4804    9367                               El Mariachi   
4805   72766                                 Newlyweds   
4806  231617                 Signed, Sealed, Delivered   
4807  126186                          Shanghai Calling   
4808   25975                         My Date with Drew   

                                                   crew  \
0     [{"credit_id": "52fe48009251416c750aca23", "de...   
1     [{"credit_id": "52fe4232c3a36847f800b579", "de...   
2     [{"credit_id": "54805967c3a36829b5002c41", "de...   
3     [{"credit_id": "52fe4781c3a36847f81398c3", "de...   
4     [{"credit_id": "52fe479ac3a36847f813eaa3", "de...   
...                                                 ...   
4804  [{"credit_id": "52fe44eec3a36847f80b280b", "de...   
4805  [{"credit_id": "52fe487dc3a368484e0fb013", "de...   
4806  [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...   
4807  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...   
4808  [{"credit_id": "58ce021b9251415a390165d9", "de...   

                                               overview  \
0     In the 22nd century, a paraplegic Marine is di...   
1     Captain Barbossa, long believed to be dead, ha...   
2     A cryptic message from Bond’s past sends him o...   
3     Following the death of District Attorney Harve...   
4     John Carter is a war-weary, former military ca...   
...                                                 ...   
4804  El Mariachi just wants to play his guitar and ...   
4805  A newlywed couple's honeymoon is upended by th...   
4806  "Signed, Sealed, Delivered" introduces a dedic...   
4807  When ambitious New York attorney Sam is sent t...   
4808  Ever since the second grade when he first saw ...   

                                                   cast  \
0     [{"cast_id": 242, "character": "Jake Sully", "...   
1     [{"cast_id": 4, "character": "Captain Jack Spa...   
2     [{"cast_id": 1, "character": "James Bond", "cr...   
3     [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4     [{"cast_id": 5, "character": "John Carter", "c...   
...                                                 ...   
4804  [{"cast_id": 1, "character": "El Mariachi", "c...   
4805  [{"cast_id": 1, "character": "Buzzy", "credit_...   
4806  [{"cast_id": 8, "character": "Oliver O\u2019To...   
4807  [{"cast_id": 3, "character": "Sam", "credit_id...   
4808  [{"cast_id": 3, "character": "Herself", "credi...   

                                                 genres  \
0     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...                                                 ...   
4804  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4805  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4806  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4807                                                 []   
4808                [{"id": 99, "name": "Documentary"}]   

                                               keywords  
0     [{"id": 1463, "name": "culture clash"}, {"id":...  
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...  
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...  
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...  
4     [{"id": 818, "name": "based on novel"}, {"id":...  
...                                                 ...  
4804  [{"id": 5616, "name": "united states\u2013mexi...  
4805         

In [10]:
import ast
def fn(oj):
    li=[]
    for i in ast.literal_eval(oj):
        li.append(i['name'])
    return li

In [11]:
movies['genres']=movies['genres'].apply(fn)

In [12]:
movies['keywords']=movies['keywords'].apply(fn)

In [13]:
import ast
def fn3(oj):
    li=[]
    count=0
    for i in ast.literal_eval(oj):
        if count!=5:
            li.append(i['name'])
            count+=1
        else:
            break
        
    return li

In [14]:
movies['cast']=movies['cast'].apply(fn3)

In [15]:
movies.head()

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                                crew  \
0  [{"credit_id": "52fe48009251416c750aca23", "de...   
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...   
2  [{"credit_id": "54805967c3a36829b5002c41", "de...   
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...   
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                                cast  \
0  [Sam Worthington, Zoe Saldana, Sigourney Weave...   
1  [Johnny Depp, Orlando Bloom, Keira Knightley, ...   
2  [Daniel Craig, Christoph Waltz, Léa Seydoux, R...   
3  [Christian Bale, Michael Caine, Gary Oldman, A...   
4  [Taylor Kitsch, Lynn Collins, Samantha Morton,...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

                                            keywords  
0  [culture clash, future, space war, space colon...  
1  [ocean, drug abuse, exotic island, east india ...  
2  [spy, based on novel, secret agent, sequel, mi...  
3  [dc comics, crime fighter, terrorist, secret i...  
4  [based on novel, mars, medallion, space travel...

In [16]:
movies['cast'].iloc[0]

['Sam Worthington',
 'Zoe Saldana',
 'Sigourney Weaver',
 'Stephen Lang',
 'Michelle Rodriguez']

In [17]:
import ast
def fn5(oj):
    li=[]
    for i in ast.literal_eval(oj):
        if i['job']=='Director' or i['job']=='Producer':
            li.append(i['name'])
    return li

In [18]:
movies['crew']=movies['crew'].apply(fn5)

In [19]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])

In [20]:
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [21]:
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])

In [22]:
movies['tags'] = movies['cast'] + movies['crew'] + movies['genres'] + movies['keywords']

In [23]:
movies.head()

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                                crew  \
0            [JamesCameron, JamesCameron, JonLandau]   
1  [GoreVerbinski, JerryBruckheimer, EricMcLeod, ...   
2      [SamMendes, BarbaraBroccoli, MichaelG.Wilson]   
3  [CharlesRoven, ChristopherNolan, ChristopherNo...   
4  [AndrewStanton, ColinWilson, JimMorris, Lindse...   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                                cast  \
0  [SamWorthington, ZoeSaldana, SigourneyWeaver, ...   
1  [JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...   
2  [DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...   
3  [ChristianBale, MichaelCaine, GaryOldman, Anne...   
4  [TaylorKitsch, LynnCollins, SamanthaMorton, Wi...   

                                         genres  \
0  [Action, Adventure, Fantasy, ScienceFiction]   
1                  [Adventure, Fantasy, Action]   
2                    [Action, Adventure, Crime]   
3              [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, ScienceFiction]   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   

                                                tags  
0  [SamWorthington, ZoeSaldana, SigourneyWeaver, ...  
1  [JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...  
2  [DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...  
3  [ChristianBale, MichaelCaine, GaryOldman, Anne...  
4  [TaylorKitsch, LynnCollins, SamanthaMorton, Wi...

In [24]:
movies['overview']=movies['overview'].apply(lambda x:str(x).split())

In [25]:

movies['tags'] = movies['cast'] + movies['crew'] + movies['genres'] + movies['keywords']+movies['overview']

In [26]:
reqdata=movies[['id','title','tags']]

In [27]:
reqdata

id                                     title  \
0      19995                                    Avatar   
1        285  Pirates of the Caribbean: At World's End   
2     206647                                   Spectre   
3      49026                     The Dark Knight Rises   
4      49529                               John Carter   
...      ...                                       ...   
4804    9367                               El Mariachi   
4805   72766                                 Newlyweds   
4806  231617                 Signed, Sealed, Delivered   
4807  126186                          Shanghai Calling   
4808   25975                         My Date with Drew   

                                                   tags  
0     [SamWorthington, ZoeSaldana, SigourneyWeaver, ...  
1     [JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...  
2     [DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...  
3     [ChristianBale, MichaelCaine, GaryOldman, Anne...  
4     [TaylorKitsch, LynnCollins, SamanthaMorton, Wi...  
...                                                 ...  
4804  [CarlosGallardo, JaimedeHoyos, PeterMarquardt,...  
4805  [EdwardBurns, KerryBishé, MarshaDietlein, Cait...  
4806  [EricMabius, KristinBooth, CrystalLowe, GeoffG...  
4807  [DanielHenney, ElizaCoupe, BillPaxton, AlanRuc...  
4808  [DrewBarrymore, BrianHerzlinger, CoreyFeldman,...  

[4809 rows x 3 columns]

In [28]:
reqdata['tags']=reqdata['tags'].apply(lambda x:" ".join(x))

C:\Users\Shashidhar\AppData\Local\Temp\ipykernel_12160\3671782342.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reqdata['tags']=reqdata['tags'].apply(lambda x:" ".join(x))


In [29]:
reqdata

id                                     title  \
0      19995                                    Avatar   
1        285  Pirates of the Caribbean: At World's End   
2     206647                                   Spectre   
3      49026                     The Dark Knight Rises   
4      49529                               John Carter   
...      ...                                       ...   
4804    9367                               El Mariachi   
4805   72766                                 Newlyweds   
4806  231617                 Signed, Sealed, Delivered   
4807  126186                          Shanghai Calling   
4808   25975                         My Date with Drew   

                                                   tags  
0     SamWorthington ZoeSaldana SigourneyWeaver Step...  
1     JohnnyDepp OrlandoBloom KeiraKnightley Stellan...  
2     DanielCraig ChristophWaltz LéaSeydoux RalphFie...  
3     ChristianBale MichaelCaine GaryOldman AnneHath...  
4     TaylorKitsch LynnCollins SamanthaMorton Willem...  
...                                                 ...  
4804  CarlosGallardo JaimedeHoyos PeterMarquardt Rei...  
4805  EdwardBurns KerryBishé MarshaDietlein CaitlinF...  
4806  EricMabius KristinBooth CrystalLowe GeoffGusta...  
4807  DanielHenney ElizaCoupe BillPaxton AlanRuck Zh...  
4808  DrewBarrymore BrianHerzlinger CoreyFeldman Eri...  

[4809 rows x 3 columns]

In [30]:
reqdata['tags'][1]

"JohnnyDepp OrlandoBloom KeiraKnightley StellanSkarsgård ChowYun-fat GoreVerbinski JerryBruckheimer EricMcLeod ChadOman PeterKohn PatSandston Adventure Fantasy Action ocean drug abuse exotic island east india trading company love of one's life traitor shipwreck strong woman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems."

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
vec=CountVectorizer(max_features=5000,stop_words='english')

In [32]:
vector=vec.fit_transform(reqdata['tags']).toarray()

In [1]:
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable


In [34]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [37]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))

    return  " ".join(y)
        

In [38]:
reqdata['tags'].apply(stem)

0       samworthington zoesaldana sigourneyweav stephe...
1       johnnydepp orlandobloom keiraknightley stellan...
2       danielcraig christophwaltz léaseydoux ralphfie...
3       christianbal michaelcain garyoldman annehathaw...
4       taylorkitsch lynncollin samanthamorton willemd...
                              ...                        
4804    carlosgallardo jaimedehoyo petermarquardt rein...
4805    edwardburn kerrybishé marshadietlein caitlinfi...
4806    ericmabiu kristinbooth crystallow geoffgustafs...
4807    danielhenney elizacoup billpaxton alanruck zhu...
4808    drewbarrymor brianherzling coreyfeldman ericro...
Name: tags, Length: 4809, dtype: object

In [39]:
reqdata['tags']=reqdata['tags'].apply(stem)

C:\Users\Shashidhar\AppData\Local\Temp\ipykernel_12160\4250218715.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reqdata['tags']=reqdata['tags'].apply(stem)


In [42]:
from sklearn.metrics.pairwise import cosine_similarity

In [46]:
similardist=cosine_similarity(vector)

In [48]:
list(enumerate(similardist))

[(0,
  array([1.        , 0.06810052, 0.03299144, ..., 0.03405026, 0.01898316,
         0.        ])),
 (1,
  array([0.06810052, 1.        , 0.04212627, ..., 0.04347826, 0.        ,
         0.        ])),
 (2,
  array([0.03299144, 0.04212627, 1.        , ..., 0.02106314, 0.        ,
         0.        ])),
 (3,
  array([0.02253745, 0.02877772, 0.08364858, ..., 0.07194431, 0.0481311 ,
         0.04413674])),
 (4,
  array([0.30550505, 0.07430376, 0.07199323, ..., 0.01857594, 0.        ,
         0.        ])),
 (5,
  array([0.12235506, 0.13670415, 0.05676567, ..., 0.05858749, 0.02177518,
         0.01996808])),
 (6,
  array([0.02434322, 0.03108349, 0.0451754 , ..., 0.        , 0.01732917,
         0.01589104])),
 (7,
  array([0.11925696, 0.09517337, 0.12909944, ..., 0.03806935, 0.        ,
         0.        ])),
 (8,
  array([0.04082483, 0.0521286 , 0.05050763, ..., 0.0521286 , 0.05812382,
         0.10660036])),
 (9,
  array([0.0751646 , 0.05758592, 0.05579525, ..., 0.03839062, 0.0214

In [53]:
sorted(list(enumerate(similardist[0])),reverse=True,key=lambda x:x[1])[1:7] #sort on the basis of dist

[(2409, 0.4548588261473419),
 (1537, 0.421089084774252),
 (3163, 0.4060812243681228),
 (838, 0.3965840535934668),
 (4338, 0.39594721055765386),
 (373, 0.3787012465603215)]

In [64]:
def recommend(movie):
    movie_index=reqdata[reqdata['title']==movie].index[0]
    distance=similardist[movie_index]
    movielist=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:7]
    
    for i in movielist:
        print(i[0])
        print(reqdata.iloc[i[0]].title)
       

In [65]:
recommend("Batman Begins")

65
The Dark Knight
1363
Batman
3
The Dark Knight Rises
1362
Batman
210
Batman & Robin
3826
Defendor


In [66]:
reqdata.iloc[65]

id                                                     155
title                                      The Dark Knight
tags     christianbal heathledg aaroneckhart michaelcai...
Name: 65, dtype: object